job/urls.py
#from django.conf.urls import patterns, url, include
from django.conf.urls import *
from django.conf import settings

from django.views import static
import job.views as jobs
import notification.views as notifications

urlpatterns = [
    url(r'^$', jobs.index),
    url(r'^type/(?P<type_name>[\w|\W]+)/$', jobs.index),
    url(r'^tags/(?P<tag_name>[\w|\W]+)/$', jobs.index),
    url(r'^category/(?P<category_name>[\w|\W]+)/$', jobs.index),
    url(r'^category/(?P<category_name>\w+)/type/(?P<type_name>\w+)/$', jobs.index),
    url(r'^show/(?P<job_name>[\w|\W]+)/(?P<job_id>\d+)/$', jobs.detail),
    url(r'^apply/(?P<job_id>\d+)/$', jobs.apply_job),
    url(r'^search$', jobs.results_search),
    url(r'^new/region$', jobs.update_region),
    url(r'^new$', jobs.new_job),
    url(r'^about-us$', jobs.about_us),
    url(r'^applied-for$', jobs.applied),
    url(r'^my-jobs$', jobs.my_jobs),
	url(r'^edit/(?P<job_id>\d+)/$', jobs.edit_job),
	url(r'^expire/(?P<job_id>\d+)/$', jobs.expire_job),
	url(r'^applications/(?P<job_name>[\w|\W]+)/(?P<job_id>\d+)/$', jobs.applications),
    url(r'^dump/', notifications.view_message_dump),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', static.serve,
            {'document_root': settings.MEDIA_ROOT,})
    ]

oddit/urls.py
#from django.conf.urls import patterns, url, include
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import admin, admindocs
from django.conf.urls import *
import job.views as jobs
admin.autodiscover()

urlpatterns = [
    # url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    # url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('job.urls')),
    #url(r'^', lambda r: HttpResponseRedirect('jobs/')),
    url(r'^search/', include('haystack.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^my-profile$', jobs.profile),
    url(r'^my-profile/edit$', jobs.settings),
    url(r'^profile/(?P<user_id>\d+)/$$', jobs.view_profile),
]

job/models.py
import time
import datetime
from django.db import models
from django.contrib.auth.models import User
from tagging.models import Tag
from django.db.models.signals import post_save
from django.forms import ModelForm
from job.validators import validate_pdf

from channels import Channel

# Create your models here.
class Region(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Regions"

class City(models.Model):
    name = models.CharField(max_length=30)
    region = models.ForeignKey(Region)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Cities"

class Category(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

class JobType(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Job Types"

class Job(models.Model):
    REMOTE_CHOICES = (
            (0, 'No'),
            (1, 'Yes')
    )
    POSITION_CHOICES = (
        (0, 'Junior'),
        (1, 'Intermediate'),
        (2, 'Senior'),
	(3, 'Intern')
    )
    STATUS_CHOICES = (
        (0, 'Draft'),
        (1, 'Published'),
        (2, 'Expired')
    )
    user = models.ForeignKey(User)
    title = models.CharField(max_length=30)
    category = models.ForeignKey(Category)
    description = models.TextField()
    position = models.IntegerField(default=0, choices=POSITION_CHOICES)
    region = models.ForeignKey(Region)
    city = models.ForeignKey(City)
    remote = models.IntegerField(default=1, choices=REMOTE_CHOICES)
    created = models.DateField(editable=False)
    updated = models.DateTimeField(editable=False)
    type = models.ForeignKey(JobType)
    budget = models.IntegerField()
    ip = models.GenericIPAddressField(default="225.225.225.225")
    status = models.IntegerField(default=1, choices=STATUS_CHOICES)
    expires = models.DateField()
    featured = models.NullBooleanField()
    bold = models.NullBooleanField()
    tag_list = models.CharField(max_length=255)

    def save(self, *args, **kwargs):
        if not self.id:
            self.created = datetime.date.today()
        self.updated = datetime.datetime.today()

        super(Job, self).save()

        self.tags = self.tag_list

    def _get_tags(self):
        return Tag.objects.get_for_object(self)

    def _set_tags(self, tag_list):
        Tag.objects.update_tags(self, tag_list)

    tags = property(_get_tags, _set_tags)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Jobs"

class JobApply(models.Model):
    user = models.ForeignKey(User)
    job = models.ForeignKey(Job)
    notes = models.TextField()
    created = models.DateField(editable=False)
    updated = models.DateTimeField(editable=False)
    resume = models.FileField(upload_to='resumes/', validators=[validate_pdf])

    def save(self, *args, **kwargs):
        if not self.id:
            self.created = datetime.date.today()
        self.updated = datetime.datetime.today()
        
        Channel("lobby-messages").send({
            "sender": self.user.id,
            "assignee": self.job.user.id,
            "job": self.job.id,
            "action": "applied to",
            "message": "%s applied to %s" % (self.user.username, self.job.title) ,
        });

        super(JobApply, self).save()

    def __unicode__(self):
        return u"%s's application" % self.user

    class Meta:
        verbose_name_plural = 'Job Applications'
        verbose_name = 'Job Application'

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    location = models.CharField(max_length=30, blank=True)
    phone = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return u"%s's profile" % self.user

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)

post_save.connect(create_user_profile, sender=User)

job/views.py
# Create your views here.
import operator, datetime, sys

from django.template import Context, loader, RequestContext
from django.template.loader import render_to_string
from job.models import Job, Category, JobType, Tag, City, JobApply, User
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render_to_response, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from job.forms import JobForm, ApplyForm, UserProfileForm
from django.template.context_processors import csrf
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import JsonResponse
from  django.utils.datastructures  import  MultiValueDictKeyError
from django.template.defaultfilters import slugify

def index(request, category_name='all', type_name='all'):
    popular_categories_list = Job.objects.values('category', 'category__name').annotate(num_jobs=Count("id")).distinct()
    popular_tags = Tag.objects.usage_for_model(Job, counts=True)[:5]
    popular_tags.sort(key=operator.attrgetter('count'), reverse=True)
    category_list = Category.objects.all()[:10]

    category_name = category_name.replace("-", " ") # url is slugified
    type_name = type_name.replace("-", " ")
    if category_name and category_name != 'all' and type_name and type_name == 'all':
        latest_job_list = Job.objects.filter(status=1,category__name__iexact=category_name).order_by('created')
    elif category_name and category_name != 'all' and type_name and type_name != 'all':
        latest_job_list = Job.objects.filter(status=1,category__name__iexact=category_name,type__name__iexact=type_name).order_by('created')
    elif  category_name and category_name == 'all' and type_name and type_name != 'all':
        latest_job_list = Job.objects.filter(status=1,type__name__iexact=type_name).order_by('created')
    else:
        latest_job_list = Job.objects.filter(status=1).order_by('created')

    total_jobs = Job.objects.count()
    job_types = JobType.objects.all()

    paginator = Paginator(latest_job_list, 10)

    page = request.GET.get('page')
    try:
        latest_job_list = paginator.page(page)
    except PageNotAnInteger:
        latest_job_list = paginator.page(1)
    except EmptyPage:
        latest_job_list = paginator.page(paginator.num_pages)
    except:
        latest_job_list = paginator.page(1)

    return render_to_response('jobs/index.html', {'latest_job_list': latest_job_list,
                                                  'categories': category_list,
                                                  'popular_categories': popular_categories_list,
                                                  'total_jobs': total_jobs,
                                                  'job_types': job_types,
                                                  'popular_tags': popular_tags,
                        						  'category_name': category_name,
                                                  'type_name': type_name,
                                                 }, context_instance=RequestContext(request))

def detail(request, job_id, job_name):
    popular_categories_list = Job.objects.values('category', 'category__name').annotate(num_jobs=Count("id")).distinct()
    popular_tags = Tag.objects.usage_for_model(Job, counts=True)[:5]
    popular_tags.sort(key=operator.attrgetter('count'), reverse=True)
    category_list = Category.objects.all()[:10]

    job = get_object_or_404(Job, pk=job_id)

    job_tags = job.tag_list.split(',');

    try:
        checkApply = JobApply.objects.get(user=request.user.id, job=job)
    except JobApply.DoesNotExist:
        checkApply = None

    return render_to_response('jobs/job.html', {
        'job': job,
        'job_tags': job_tags,
        'applied': checkApply,
        'categories': category_list,
        'popular_categories': popular_categories_list,
        'popular_tags': popular_tags,},
        context_instance=RequestContext(request))


def results_search(request):
    popular_categories_list = Job.objects.values('category', 'category__name').annotate(num_jobs=Count("id")).distinct()
    popular_tags = Tag.objects.usage_for_model(Job, counts=True)[:5]
    popular_tags.sort(key=operator.attrgetter('count'), reverse=True)
    category_list = Category.objects.all()[:10]
    job_types = JobType.objects.all()


    try:
        query = request.GET['query']
    except (InvalidQuery, MultiValueDictKeyError), e:
        return render_to_response('jobs/search_results.html', {
                                                           'categories': category_list,
                                                           'popular_categories': popular_categories_list,
                                                           'job_types': job_types,
                                                           'popular_tags':
                                                           popular_tags}, context_instance=RequestContext(request))

    total_jobs = Job.objects.count()
    job_types = JobType.objects.all()

    jobs = Job.objects.filter(title__icontains=query) | \
            Job.objects.filter(tag_list__icontains=query) | \
            Job.objects.filter(description__icontains=query)

    total_jobs = Job.objects.count()

    return render_to_response('jobs/search_results.html', {'query': query,
                                                           'job_list': jobs,
                                                           'categories': category_list,
                                                           'popular_categories': popular_categories_list,
                                                           'total_jobs': total_jobs,
                                                           'job_types': job_types,
                                                           'popular_tags':
                                                           popular_tags}, context_instance=RequestContext(request))


@login_required
def apply_job(request, job_id):
    popular_categories_list = Job.objects.values('category', 'category__name').annotate(num_jobs=Count("id"))
    popular_tags = Tag.objects.usage_for_model(Job, counts=True)[:5]
    popular_tags.sort(key=operator.attrgetter('count'), reverse=True)
    category_list = Category.objects.all()[:10]

    j = get_object_or_404(Job, pk=job_id)
    try:
       checkApply = JobApply.objects.get(user=request.user, job=j)
       errors = 'You have already applied for this job'
       return render_to_response('jobs/apply_job.html',  {
           'errors' : errors,
           'popular_categories': popular_categories_list,
           'popular_tags': popular_tags,
           'categories': category_list,
           'job': j,},
            context_instance=RequestContext(request))


    except JobApply.DoesNotExist:
       app = JobApply(user=request.user, job=j)

       if request.method == 'POST':
          errors = 'aaaa'
          form = ApplyForm(request.POST, request.FILES, instance=app, user=request.user, job=j)

          msg = 'Dear ' + j.user.first_name + ',\n\n' + app.user.first_name + ' ' + app.user.last_name + ' has applied for your job "' + j.title + '".\n\nDownload their CV now and get in touch'

          if form.is_valid():
             form.save()

             app_url = request.build_absolute_uri('/applications/%s/%s' % (slugify(j.title), j.id))
             msg_plain = render_to_string('jobapplicationemail.txt', {'j': j, 'app': app, 'app_url': app_url})
             msg_html  = render_to_string('jobapplicationemail.html', {'j': j, 'app': app, 'app_url': app_url})

             send_mail('Someone applied for your Job ', msg_plain, 'mike@oddit.co.nz', [j.user.email], html_message=msg_html, fail_silently=False)
             return HttpResponseRedirect('/applied-for')
          else:
            return JsonResponse(form.errors.as_json(), safe=False, status=400)
       else:
          form = ApplyForm(instance=app, user=request.user, job=j)

       return render_to_response('jobs/apply_job.html',  {
           'form' : form,
           'popular_categories': popular_categories_list,
           'popular_tags': popular_tags,
           'categories': category_list,
           'job': j,},
            context_instance=RequestContext(request))

@login_required
def applied(request):
    popular_categories_list = Job.objects.values('category', 'category__name').annotate(num_jobs=Count("id"))
    popular_tags = Tag.objects.usage_for_model(Job, counts=True)[:5]
    popular_tags.sort(key=operator.attrgetter('count'), reverse=True)
    category_list = Category.objects.all()[:10]

    applied = JobApply.objects.filter(user=request.user).values_list('job_id', flat=True)
    jobs = Job.objects.filter(id__in=applied)

    return render_to_response('jobs/applied.html',  {
        'popular_categories': popular_categories_list,
        'popular_tags': popular_tags,
        'categories': category_list,
        'job_list': jobs,},
        context_instance=RequestContext(request))

@login_required
def my_jobs(request):
    popular_categories_list = Job.objects.values('category', 'category__name').annotate(num_jobs=Count("id"))
    popular_tags = Tag.objects.usage_for_model(Job, counts=True)[:5]
    popular_tags.sort(key=operator.attrgetter('count'), reverse=True)
    category_list = Category.objects.all()[:10]

    myjobs = Job.objects.filter(user=request.user)

    return render_to_response('jobs/my_jobs.html', {
        'popular_categories': popular_categories_list,
        'popular_tags': popular_tags,
        'categories': category_list,
        'job_list': myjobs,},
        context_instance=RequestContext(request))

@login_required

templates/jobs/about_us.html
{% extends "jobs/base.html" %}
{% block content %}

<div class="focus">
	<div class="listing whiteboard">
		<div class="title white">
			<h1>Sample Page</h1>
		</div>
		<div class="description cms">
			<p>This is an example page. It&#8217;s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:</p>
			<blockquote><p>Hi there! I&#8217;m a bike messenger by day, aspiring actor by night, and this is my blog. I live in Los Angeles, have a great dog named Jack, and I like pi&#241;a coladas. (And gettin&#8217; caught in the rain.)</p></blockquote>
			<p>&#8230;or something like this:</p>
			<blockquote><p>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickies to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</p></blockquote>
			<p>As a new WordPress user, you should go to <a href="http://oddit.co.nz/wordpress/wp-admin/">your dashboard</a> to delete this page and create new pages for your content. Have fun!</p>
		</div>
		<div class="cap"></div>
	</div>
</div>

{% endblock %}

templates/jobs/applications.html
{% extends "jobs/base.html" %}
{% block content %}

	<div class="results whiteboard">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-page-title">Applications for {{job}}</h2>
			</div>
			<ol class="list-group">
				{% for app in applications %}
					<li class="list-group-item">
						<div class="details">
							<h3>
                                {% if not user.first_name %}
                                    <a href="">{{ user.username }}</a>
                                {% else %}
                                    <a href="">{{ user.first_name }} {{ app.user.last_name }}</a>
                                {% endif %}
							</h3>
							<div class="company">
									<div class="panel-body">
										{{ app.notes|safe }}
									</div>
							</div>
						</div>
						<div class="meta container-fluid">
							<span>Submitted: {{ app.created }}</span>
							<a class="pull-right btn btn-primary" href="{{MEDIA_URL}}{{ app.resume }}">Résumé Download</a>
						</div>
					</li>
					{% empty %}
					<li class="list-group-item">
						This job doesn't have any applications.
					</li>
				{% endfor %}
			</ol>
		</div>
		<div class="cap"></div>

	</div>
{% endblock %}

templates/jobs/applied.html
{% extends "jobs/base.html" %}
{% block content %}
{% load markdownify %}
	<div class="results whiteboard">

		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-page-title">Jobs you've applied for</h2>
			</div>
			<ol class="list-group">
				{% for job in job_list %}
					<li class="list-group-item design filter_2">
						<div class="details">
							<h3>
								<a href="show/{{ job.title|slugify }}/{{ job.id}}">{{ job.title }}</a>
							</h3>
						</div>
						<div class="meta">
							<dl>
								<dt>{{ job.city }},
									{{ job.region }}</dt>
								<dd>{{ job.get_type_display }}</dd>
							</dl>
						</div>
                        <div class="meta">
                            {% for app in job.jobapply_set.all %}
                                {% if app.user.id = user.id %}
                                    <div>
                                        <p>Notes: </p>
																				<div class="well well-sm">
																					{{ app.notes|safe }}
																				</div>
                                    </div>
                                    <div>
                                        <span>Résumé: <a href="{{MEDIA_URL}}{{ app.resume }}">download</a></span>
                                    </div>
                                    <div>
                                        <span>Applied: {{ app.created }}</span>
                                    </div>
                                 {% endif %}
                            {% endfor %}
						</div>
					</li>
					{% empty %}
					<li class="list-group-item design_filter_2">
						You have not applied for any jobs.
					</li>
				{% endfor %}
			</ol>

			<div class="cap"></div>
		</div>

	</div>
{% endblock %}

templates/jobs/apply_job.html
{% extends "jobs/base.html" %}
{% load bootstrap %}
{% load widget_tweaks %}
{% block content %}
	{% load wysiwyg %}
	{% load markdownify %}
	<div class="post whiteboard">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-page-title">Apply for this position</h2>
				<p>
					For help,
					<a href="#">click here</a>
				</p>
			</div>

			<form id="post" enctype="multipart/form-data" name="post" action="" method="post">{% csrf_token %}
				<div class="panel-body">
					<div class="form-group {% if form.resume.errors %} has-error {% endif %}">
						<label for="inputEmail3" class="col-sm-2 control-label">{{ form.resume.label_tag }}</label>
						<div class="col-sm-10">
							{{ form.resume|attr:'required:true'}}
							<div class="help-block with-errors"></div>
						</div>
					</div>
					{% wysiwyg_setup %}
					{% wysiwyg_editor "id_notes" %}
					<div class="form-group {% if form.notes.errors %} has-error {% endif %}">
						<label for="inputEmail3" class="col-sm-2 control-label">{{ form.notes.label_tag }}</label>
						<div class="col-sm-10">
							{{ form.notes|attr:'required:true' }}
							<p class="help-block">Fill in as much detail as you can about the position, outlining responsibilities, perks and information about your company.</p>
							<div class="help-block with-errors"></div>
						</div>
					</div>

				</div>
				<div class="panel-footer clearfix">
					<input id="jobapplysubmit" name="jobapplysubmit" type="submit" value="Apply" class="btn btn-primary pull-right"/>
				</div>
			</form>
		</div>
	</div>

	<script type="text/javascript">
		$(document).ready(function () {
			$("#post").validator();
		});
	</script>
{% endblock %}

templates/jobs/detail.html
<h1>{{ job.name }}</h1>
<p>Category: {{ job.category }}</p>
<p>Description: {{ job.description }}</p>
<p>Position: {{ job.position }}</p>
<p>Where: {{ job.city }}, {{ job.region }}</p>
<p>Remote work: {{ job.get_remote_display }}</p>
<p>Application opened: {{ job.created }}</p>
<p>Last updated: {{ job.updated }}</p>
<p>Job type: {{ job.get_type_display }}</p>
<p>Wage: {{ job.wage }}</p>
<p>Posters IP: {{ job.ip }}</p>
<p>Applications close: {{ job.expires }}</p>
<p>Featured post: {{ job.featured }}</p>
<p>Bold post: {{ job.bold }}</p>

templates/jobs/new_job.html
{% extends "jobs/base.html" %}
{% load bootstrap %}
{% load widget_tweaks %}
{% load wysiwyg %}
{% load markdownify %}
{% block content %}
	<div class="post whiteboard">
		<div class="panel panel-default">
			<div class="panel-heading">
				{% if form.instance.pk %}
					<h2 class="panel-page-title">Edit Job</h2>
				{% else %}
					<h2 class="panel-page-title">Post a Job</h2>
				{% endif %}
				<p>
					For help,
					<a href="#">click here</a>
				</p>
			</div>
			<form id="post" name="post" action="" method="post" class="form-horizontal">{% csrf_token %}
				{% wysiwyg_setup %}
				<div class="panel-body">

					<div class="input-block">
						<div class="form-group {% if form.title.errors %} has-error {% endif %}">
							<label for="inputEmail3" class="col-sm-2 control-label">{{ form.title.label_tag }}</label>
							<div class="col-sm-10">
								{{ form.title|attr:'required:true'}}
								<p class="help-block">Enter a descriptive title for the job listing.</p>
								<div class="help-block with-errors"></div>
							</div>
						</div>
					</div>

					<div class="input-block">
						<div class="form-group {% if form.category.errors %} has-error {% endif %}">
							<label for="inputEmail3" class="col-sm-2 control-label">{{ form.category.label_tag }}</label>
							<div class="col-sm-10">
								{{ form.category|attr:'required:true'}}
								<p class="help-block">Select a category that best suits the job listing.</p>
								<div class="help-block with-errors"></div>
							</div>
						</div>

						{% wysiwyg_editor "id_description" %}
						<div class="form-group {% if form.description.errors %} has-error {% endif %}">
							<label for="inputEmail3" class="col-sm-2 control-label">{{ form.description.label_tag }}</label>
							<div class="col-sm-10">
								{{ form.description|attr:'required:true' }}
								<p class="help-block">Fill in as much detail as you can about the position, outlining responsibilities, perks and information about your company.</p>
								<div class="help-block with-errors"></div>
							</div>
						</div>
					</div>

					<div class="input-block">
						<div class="form-group {% if form.position.errors %} has-error {% endif %}">
							<label for="inputEmail3" class="col-sm-2 control-label">{{ form.position.label_tag }}</label>
							<div class="col-sm-10">
								{{ form.position|attr:'required:true' }}
								<div class="help-block with-errors"></div>
							</div>
						</div>
						<div class="form-group {% if form.remote.error %} has error {% endif %}">
							<label for="inputEmail3" class="col-sm-2 control-label">{{ form.remote.label_tag }}</label>
							<div class="col-sm-10">
								{{ form.remote|attr:'required:true' }}
								<p class="help-block">Can this job be worked on from a remote location?</p>
								<div class="help-block with-errors"></div>
							</div>

						</div>
					</div>

					<div class="input-block">
						<div class="form-group {% if form.region.errors %} has-error {% endif %}">
							<label for="inputEmail3" class="col-sm-2 control-label">{{ form.region.label_tag }}</label>
							<div class="col-sm-10">
								{{ form.region|attr:'required:true' }}
								<div class="help-block with-errors"></div>
							</div>
						</div>

						<div class="form-group {% if form.city.errors %} has-error {% endif %}">
							<label for="inputEmail3" class="col-sm-2 control-label">{{ form.city.label_tag }}</label>
							<div class="col-sm-10">
								{{ form.city|attr:'required:true' }}
								<div class="help-block with-errors"></div>
							</div>
						</div>
					</div>

					<div class="input-block">
						<div class="form-group {% if form.type.errors %} has-error {% endif %}">
							<label for="inputEmail3" class="col-sm-2 control-label">{{ form.type.label_tag }}</label>
							<div class="col-sm-10">
								{{ form.type|attr:'required:true' }}
								<div class="help-block with-errors"></div>
							</div>
						</div>
					</div>

					<div class="input-block">
						<div class="form-group {% if form.budget.errors %} has-error {% endif %}">
							<label for="inputEmail3" class="col-sm-2 control-label">{{ form.budget.label_tag }}</label>
							<div class="col-sm-10">
								{{ form.budget|attr:'required:true'|attr:'type:number'|attr:'step:any' }}
								<p class="help-block">Enter in the budget/wage for this job.</p>
								<div class="help-block with-errors"></div>
							</div>
						</div>
					</div>

					<div class="input-block">
						<div class="form-group {% if form.expires.errors %} has-error {% endif %}">
							<label for="inputEmail3" class="col-sm-2 control-label">{{ form.expires.label_tag }}</label>
							<div class='col-sm-10'>
								{{ form.expires|attr:'required:true' }}
								<div class="help-block with-errors"></div>
							</div>
						</div>

						<div class="form-group {% if form.tag_list.errors %} has-error {% endif %}">
							<label for="inputEmail3" class="col-sm-2 control-label">{{ form.tag_list.label_tag }}</label>
							<div class="col-sm-10">
								{{ form.tag_list|attr:'required:true' }}
								<p class="help-block">Comma seperated tags describing this job.</p>
								<div class="help-block with-errors"></div>
							</div>
						</div>
					</div>
				</div>
				<div class="panel-footer clearfix">
					<input id="jobsubmit" name="jobsubmit" type="submit" value="Submit Listing" class="btn btn-primary pull-right"/>
				</div>
			</form>
		</div>
	</div>

	<script type="text/javascript">
		$(document).ready(function () {
			$('#id_category, #id_position, #id_type, #id_budget_type').chosen({disable_search_threshold: 10});
			$('#id_remote').chosen({disable_search_threshold: 10});
			$('#id_region').chosen({disable_search_threshold: 10});
			$('#id_city').chosen({disable_search_threshold: 10});
			$('#id_tag_list').tagsinput({tagClass: 'label label-info job_tag_label'});
		});

		if (!Modernizr.touchevents || !Modernizr.inputtypes.date) {
			$('.datepicker').prop('type', 'text');
			$('.datepicker').datepicker();
		} else {}

		$(document).ready(function () {
			$.fn.validator.Constructor.INPUT_SELECTOR += ':not(.chosen-search input)'
			$("#post").validator();
			$('#id_region').on('change', function (evt, params) {
				val = this.value;
				$.post("/new/region", {
					id: val,
					'csrfmiddlewaretoken': '{{ csrf_token }}'
				}, function (data) {
					$('#id_city').find('option').remove().end();
					var rawCities = data.split('|');
					rawCities.pop();
					$('#id_city').append('<option value="" selected="selected">---------</option>');
					$.each(rawCities, function (index, value) {
						rawCity = value.split(':');
						$('#id_city').append('<option value="' + rawCity[0] + '">' + rawCity[1] + '</option>');
					});
					$("#id_city").trigger("chosen:updated");
				});
			});

		});
	</script>
{% endblock %}